enable-magisk-update = true
parallel-jobs = 1

compression-level = 9
remove-rv-integrations-checks = true

patches-source = "revanced/revanced-patches"
cli-source = "j-hc/revanced-cli"

rv-brand = "extended"

patches-version = "latest"
cli-version = "latest"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
integrations-source = "anddea/revanced-integrations"
arch = "arm64-v8a"
build-mode = "both"
included-patches = "'Custom branding icon for YouTube' 'MaterialYou'"
excluded-patches = "'Translations for YouTube'"
patcher-args = "-OappIcon=revancify_red "

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
integrations-source = "anddea/revanced-integrations"
arch = "arm64-v8a"
build-mode = "both"
included-patches = "'Custom branding icon for YouTube Music'"
excluded-patches = "'SponsorBlock'"
patcher-args = "-OappIcon=revancify_red "
