enable-magisk-update = true
parallel-jobs = 1

compression-level = 9
remove-rv-integrations-checks = true

cli-source = " inotia00/revanced-cli"
patches-version = "latest"
cli-version = "latest"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced eXtended"
arch = "arm64-v8a"
build-mode = "both"
included-patches = "'Custom header for YouTube' 'MaterialYou'"
excluded-patches = "'Custom Shorts action buttons' 'Custom branding icon for YouTube' 'Custom branding name for YouTube'"

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "ReVanced eXtended"
arch = "arm64-v8a"
build-mode = "both"
included-patches = "'Custom header for YouTube Music' 'Disable music video in album'"
excluded-patches = "'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'SponsorBlock' 'Translations for YouTube Music'"

